version: '3.8'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./Redoublet-backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./Redoublet-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    command: [nginx, '-g', 'daemon off;']
    environment:
      - NGINX_WORKER_PROCESSES=1